minisql:
  zk_url:
    localhost:3246,localhost:3246,localhost:3246
  zk_path_name:
    region_1,region_2,region_3
  region_port:
    1323,1324,1325
  shell_path:
    /home/ralxyz/Documents/temp/region1/MiniSQL,/home/ralxyz/Documents/temp/region2/MiniSQL,/home/ralxyz/Documents/temp/region3/MiniSQL
